database: 
  dbname: db_mysql-test
  dbtable: liza
pods: 
  image: lizaaliza/docker-app-demo
  tag: latest
  pullPolicy: Always

replicas: 2

service:
  type: ClusterIP
  port: 8080
  targetport: 8080
  
ingress:
  enabled: true
  className: nginx
  host: flask-app.local
